image:
  file: .gitpod.Dockerfile

tasks:
  - name: Unit Tests
    before: cd api
    init: echo "Awaiting NPM install..." && while ! find .gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    before: cd api
    init: echo "Awaiting NPM install..." && while ! find .gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn tdd:e2e
    openIn: right
    openMode: tab-after
  - name: App Tests
    before: cd app
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn tdd
    openIn: right
    openMode: tab-after
  - name: Styleguide
    before: cd app
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn start:gitpod:styleguide
    openIn: right
    openMode: tab-after
  - name: Hasura
    command: hasura_start
  - name: Api
    before: cd api
    init: yarn install && touch .gitpod.lock
    command: yarn start:gitpod
    openIn: bottom
    openMode: tab-after
  - name: App
    before: cd app
    init: yarn install && touch .gitpod.lock
    command: yarn start:gitpod:app
    openIn: bottom
    openMode: tab-after

ports:
  - port: 5432
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8008
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
